name: CI Pipeline - IPL_SCOCIAL


on :
  push:
    branches:
      -main
      -develop

  pull_request:
    branches:
      -main

jobs:
  test:
    name: Build and Test 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]


  steps:
  -name: Checkout repository
  uses: actions/checkout@v4

  name: Setup Node.js
  usess: actions/setup_node@v4
  with:
    node-version: ${{ matrix.node-version }}
    cache : 'npm'

  -name : Install dependecies
  run : npm CI

  -namee : Build Typescript
  run : npm run build

  -name: Run Tests
  run : npm test  

  -name: Generate coverage report
  run : npm run coverage
  continue-on-error: true

  -name :  Upload coverage to GitHub
  uses: actions/upload-artifact@v4
  with:
    name: coverage-report
    path: coverage/
    if: matrix.node-version == '20.x'